excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

custom_rules:
    force_cast_bis:
        included: ".*\\.swift"
        name: "Force Cast"
        regex: "[a-z]!"
        message: "Avoid using force cast"
        severity: warning
